development:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000
  encoding: unicode
test:
  adapter: postgresql
  database: my_database_test
  pool: 5
  timeout: 5000
  encoding: unicode


production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
